#!/bin/bash
# $Id: hdf5_configure_pgf15_linux 4896 2016-05-30 08:54:50Z frdo $
#
# hdf5 (v1.8.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: pgf15 / Linux (Portland v15)
#
PREFIX=${1-$LIBS_ROOT/pgf15}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
pgf15 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
FC=pgf15 \
CC=gcc     CFLAGS="-O2 -w" \
         CPPFLAGS="-I$PREFIX/include" \
          LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64 -L/opt/pgi/linux86/$ver/lib" \
  ./configure --disable-shared --prefix=$PREFIX
