#!/bin/bash
# $Id: hdf5_configure_pgf95_linux 45 2016-03-02 10:20:55Z frdo $
#
# hdf5 (v1.8.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: pgf95 / Linux (Portland local default)
#
PREFIX=${1-$LIBS_ROOT/pgf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
pgf95 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
FC=pgf95 \
CC=gcc     CFLAGS="-O2 -w" \
         CPPFLAGS="-I$PREFIX/include" \
          LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64 -L/opt/pgi/linux86/$ver/lib" \
  ./configure --disable-shared --prefix=$PREFIX
