#!/bin/bash
# $Id: hdf5_configure_g95_cygwin 3007 2011-09-05 15:45:37Z frdo $
#
# hdf5 (v1.8.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: g95 / Cygwin
#
PREFIX=${1-$LIBS_ROOT/g95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
g95 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
FC=g95 \
CC=gcc     CFLAGS="-O2 -w" \
         CPPFLAGS="-I$PREFIX/include" \
          LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
  ./configure --disable-shared --prefix=$PREFIX
