#!/bin/bash
# $Id: netcdf_configure_pgf14_linux 4896 2016-05-30 08:54:50Z frdo $
#
# netcdf (4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: pgf14 / Linux (Portland v14)
#
PREFIX=${1-$LIBS_ROOT/pgf14}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
pgf14 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
FC=pgf14 \
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include" \
            LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
  ./configure --disable-v2 --disable-dap --disable-shared --prefix=$PREFIX
