#!/bin/bash
# $Id: netcdff_configure_nagfor52_linux 4896 2016-05-30 08:54:50Z frdo $
#
# netcdf-fortran (v4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: nagfor52 / Linux (NAGWare v5.2)
#
PREFIX=${1-$LIBS_ROOT/nagfor52}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
nagfor52 -V
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include" \
FC=nagfor52 FCFLAGS="-O2 -w -dusty -ieee=full" \
F77=nagfor52 FFLAGS="-O2 -w -dusty -ieee=full" \
            LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
               LIBS="-lhdf5 -lhdf5_hl -lnetcdf" \
  ./configure --disable-shared --prefix=$PREFIX
