#!/bin/bash
# $Id: netcdff_configure_g95_cygwin 4736 2016-03-07 15:20:06Z frdo $
#
# netcdf-fortran (v4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: g95 / Cygwin
#
PREFIX=${1-$LIBS_ROOT/g95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
g95 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include" \
FC=g95      FCFLAGS="-O2" \
            LDFLAGS="-L$PREFIX/lib" \
               LIBS="-lhdf5 -lhdf5_hl -lnetcdf" \
  ./configure --disable-shared --prefix=$PREFIX
