#!/bin/bash
# $Id: netcdf_configure_ifort16_linux 4896 2016-05-30 08:54:50Z frdo $
#
# netcdf (4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: ifort16 / Linux (Intel v16)
#
PREFIX=${1-$LIBS_ROOT/ifort16}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort16 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
FC=ifort16 \
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include" \
            LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
  ./configure --disable-v2 --disable-dap --disable-shared --prefix=$PREFIX
