#!/bin/bash
# $Id: netcdff_configure_pgf11_linux 4896 2016-05-30 08:54:50Z frdo $
#
# netcdf-fortran (v4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: pgf11 / Linux (Portland v11)
#
PREFIX=${1-$LIBS_ROOT/pgf11}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
pgf11 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include" \
FC=pgf11    FCFLAGS="-O2 -w" \
F77=pgf11    FFLAGS="-O2 -w" \
            LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
               LIBS="-lhdf5 -lhdf5_hl -lnetcdf" \
  ./configure --disable-shared --prefix=$PREFIX
