#!/bin/bash
# $Id: netcdf_configure_g95_linux 5220 2017-02-21 13:34:29Z idculv $
#
# netcdf (4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: g95 / Linux (G95 local default)
#
PREFIX=${1-$LIBS_ROOT/g95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
g95 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
FC=g95 \
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include -DDUNDERSCORE" \
            LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64"   \
  ./configure --disable-v2 --disable-dap --disable-shared --prefix=$PREFIX
