#!/bin/bash
# $Id: netcdf_configure_sunf95_linux-suncc 4998 2016-07-08 20:28:24Z frdo $
#
# netcdf-c (v4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: sunf95 / Linux (Oracle local default)
#
PREFIX=${1-$LIBS_ROOT/sunf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
sunf95 -V
echo
echo "C compiler:"
suncc -V
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
FC=sunf95 \
CC=suncc     CFLAGS="-O -w -m64" \
           CPPFLAGS="-I$PREFIX/include -DsunFortran" \
            LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
  ./configure --disable-shared --disable-v2 --disable-dap --prefix=$PREFIX

# NOTE: suncc   cannot build shared libaries, hence the --disable-shared flag.
# Alternatively, use CC=gcc in which case remove flags -m64 and
# (optionally) --disable-shared
