#!/bin/bash
# $Id: netcdf_configure_gfortran_cygwin 5220 2017-02-21 13:34:29Z idculv $
#
# netcdf (4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: gfortran / Cygwin (GCC local default)
#
PREFIX=${1-$LIBS_ROOT/gfortran}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
gfortran --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
FC=gfortran \
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include" \
            LDFLAGS="-L$PREFIX/lib" \
  ./configure --disable-v2 --disable-dap --disable-shared --prefix=$PREFIX
