#!/bin/bash
# $Id: netcdff_configure_ftn_linux 4896 2016-05-30 08:54:50Z frdo $
#
# netcdf-fortran (v4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: (Cray HPC) ftn / Linux
#
PREFIX=${1-$LIBS_ROOT/ftn}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ftn -V
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include" \
FC=ftn      FCFLAGS="-O2 -m4 -ef"   \
F77=ftn     FCFLAGS="-O2 -m4 -ef"   \
            LDFLAGS="-L$PREFIX/lib" \
               LIBS="-lhdf5 -lhdf5_hl -lnetcdf" \
  ./configure --disable-shared --prefix=$PREFIX
