#!/bin/bash
# $Id: netcdf_configure_xlf95_aix 5220 2017-02-21 13:34:29Z idculv $
#
# netcdf (v4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: xlf95 / IBM AIX
#
PREFIX=${1-$LIBS_ROOT/xlf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
xlf95 -qversion
echo
echo "C compiler:"
xlc -qversion
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
FC=xlf95 \
CC=xlc       CFLAGS="-O2 -w -q64"       \
           CPPFLAGS="-I$PREFIX/include" \
            NMFLAGS="-X64" ARFLAGS="-X64 cru" \
            LDFLAGS="-L$PREFIX/lib" \
  ./configure --disable-v2 --disable-shared --prefix=$PREFIX
