#!/bin/bash
# $Id: netcdf_configure_pgf11_linux 5220 2017-02-21 13:34:29Z idculv $
#
# netcdf (4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: pgf11 / Linux (Portland v11)
#
PREFIX=${1-$LIBS_ROOT/pgf11}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
pgf11 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
FC=pgf11 \
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include" \
            LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
  ./configure --disable-v2 --disable-dap --disable-shared --prefix=$PREFIX
