#!/bin/bash
# $Id: netcdff_configure_local 4896 2016-05-30 08:54:50Z frdo $
#
# netcdf-fortran (v4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Default: ifort / Linux
#
PREFIX=${1-$HOME}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include" \
FC=ifort    FCFLAGS="-O2 -w" \
F77=ifort    FFLAGS="-O2 -w" \
            LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
               LIBS="-lhdf5 -lhdf5_hl -lnetcdf" \
  ./configure --disable-shared --prefix=$PREFIX
