#!/bin/bash
# $Id: netcdff_configure_efc_linux 4736 2016-03-07 15:20:06Z frdo $
#
# netcdf-fortran (v4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: efc / Linux
#
PREFIX=${1-$LIBS_ROOT/efc}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
efc -V
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include" \
FC=efc      FCFLAGS="-O2 -integer_size 64 -cm -w"   \
F77=efc      FFLAGS="-O2 -integer_size 64 -cm -w"   \
            LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
               LIBS="-lhdf5 -lhdf5_hl -lnetcdf" \
  ./configure --disable-shared --prefix=$PREFIX
