#!/bin/bash
# $Id: netcdff_configure_sunf95_linux 5007 2016-07-13 11:11:48Z frdo $
#
# netcdf-fortran (v4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: sunf95 / Linux (Oracle local default) [with gcc]
#
PREFIX=${1-$LIBS_ROOT/sunf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
sunf95 -V
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc      CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include -DsunFortran" \
FC=sunf95  FCFLAGS="-O -w -m64 -moddir=./" \
F77=sunf95 FCFLAGS="-O -w -m64 -moddir=./" \
            LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
               LIBS="-lhdf5 -lhdf5_hl -lnetcdf" \
  ./configure --disable-shared --prefix=$PREFIX

# NOTE: sunf95 cannot build shared libaries,
# hence the --disable-shared flag.
