#!/bin/bash
# $Id: netcdf_configure_ifort14_linux 48 2016-03-02 21:34:41Z frdo $
#
# netcdf (4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: ifort14 / Linux (Intel v14)
#
PREFIX=${1-$LIBS_ROOT/ifort14}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort14 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
FC=ifort14 \
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include" \
            LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
  ./configure --disable-v2 --disable-dap --disable-shared --prefix=$PREFIX
