#!/bin/bash
# $Id: netcdf_configure_ftn_linux 4896 2016-05-30 08:54:50Z frdo $
#
# netcdf (4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: ftn / Linux
#
PREFIX=${1-$LIBS_ROOT/ftn}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ftn -V
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
FC=ftn \
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include" \
            LDFLAGS="-L$PREFIX/lib" \
  ./configure --disable-v2 --disable-dap --disable-shared --prefix=$PREFIX
