#!/bin/bash
# $Id: netcdf_configure_nagfor60_linux 4896 2016-05-30 08:54:50Z frdo $
#
# netcdf (4.4.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: nagfor60 / Linux (NAGWare v6.0)
#
PREFIX=${1-$LIBS_ROOT/nagfor60}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
nagfor60 -V
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
FC=nagfor60 \
CC=gcc       CFLAGS="-O2 -w" \
           CPPFLAGS="-I$PREFIX/include" \
            LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
  ./configure --disable-v2 --disable-dap --disable-shared --prefix=$PREFIX
