#!/bin/bash
# $Id: zlib_configure_ifort13_linux 45 2016-03-02 10:20:55Z frdo $
#
# zlib (v1.2.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: ifort13 / Linux (Intel v13)
#
PREFIX=${1-$LIBS_ROOT/ifort13}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort13 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc        CFLAGS="-O2 -w" \
  ./configure --static --prefix=$PREFIX
