#!/bin/bash
# $Id: zlib_configure_local 4896 2016-05-30 08:54:50Z frdo $
#
# zlib (v1.2.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Default: ifort / Linux
#
PREFIX=${1-$HOME}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc        CFLAGS="-O2 -w" \
  ./configure --static --prefix=$PREFIX
