#!/bin/bash
# $Id: zlib_configure_ifort15_linux 4896 2016-05-30 08:54:50Z frdo $
#
# zlib (v1.2.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: ifort15 / Linux (Intel v15)
#
PREFIX=${1-$LIBS_ROOT/ifort15}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort15 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc        CFLAGS="-O2 -w" \
  ./configure --static --prefix=$PREFIX
