#!/bin/bash
# $Id: zlib_configure_sunf95_linux-suncc 4736 2016-03-07 15:20:06Z frdo $
#
# zlib (v1.2.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: sunf95 / Linux
#
PREFIX=${1-$LIBS_ROOT/sunf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
sunf95 -V
echo
echo "C compiler:"
suncc -V
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=suncc  CFLAGS="-O -w -m64 -fPIC" \
  ./configure --static --prefix=$PREFIX


# NOTE: suncc   cannot build shared libaries, hence the --static flag;
# the -fPIC flag is needed else HDF5 complains about being unable
# to relocate code. Alternatively, use CC=suncc in which case remove
# flags -m64, -fPIC and (optionally) --static
