#!/bin/bash
# $Id: zlib_configure_sunf95_linux 45 2016-03-02 10:20:55Z frdo $
#
# zlib (v1.2.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: sunf95 / Linux (Oracle local default) with gcc
#
PREFIX=${1-$LIBS_ROOT/sunf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
sunf95 -V
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc        CFLAGS="-O2 -w" \
  ./configure --static --prefix=$PREFIX
