#!/bin/bash
# $Id: zlib_configure_nagfor60_linux 4896 2016-05-30 08:54:50Z frdo $
#
# zlib (v1.2.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: nagfor60 / Linux (NAGWare v6.0)
#
PREFIX=${1-$LIBS_ROOT/nagfor60}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
nagfor60 -V
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc        CFLAGS="-O2 -w" \
  ./configure --static --prefix=$PREFIX
